name: sermo.farm
favicon: null
layout_spectrum: 0.39908
typography_spectrum: 0.6832449268549681
title: Cultivated Content
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.05624975054524839
  lightness: 0.9352310125250369
  saturation: 0.4084242368116975
  rhythmicContrast: 0.2600090226624161
purpose: []
